model_args:
  pretrained_model_name_or_path: "openai-community/gpt2"
tokenizer_args:
  pretrained_model_name_or_path: "openai-community/gpt2"
template_args:
  apply_chat_template: False
  user_start_tag: "Question: "
  user_end_tag: "\n"
  asst_start_tag: "Answer: "
  asst_end_tag: "\n\n"
